### ISSUE TITLE
there is no suc_gmm_model in train models.

### ISSUE THREAD

**Issue by WanyiLi** [QingkaiLu/multi-fingered_grasp_planners#2]
Hi, QingKai.

When I run step 4 in part III of the grasp pipeline, i.e., roslaunch prob_grasp_planner grasp_active_learning.launch, an error occurs as follows.
"IOError: [Errno 2] No such file or directory: u'/home/ubuntu/gazebo9_ws/src/prob_grasp_planner/models/grasp_al_prior/suc_gmm_10_sets'
"
I checked the trained models from the link provide at https://robot-learning.cs.utah.edu/project/grasp_voxel_inference， i.e., https://drive.google.com/file/d/1_64nTCnuNLs52eKJqo3C2JAejjx0vlAm/view. It is true that there is no suc_gmm_model and suc_mdn_modelin dir model/grasp_al_prior/.

Could you provide the trained suc_gmm_model and suc_mdn_model?
Thanks.

**Comment by QingkaiLu** [comment]
Hi Wanyi,

The models of the grasp planning methods reported in our RAM [paper](https://arxiv.org/abs/2001.09242) can be found in that google drive link. The success 10 sets models only use the successful grasps for training, which doesn't work as well as the models trained both successful and failure grasps. We didn't include the success 10 sets models in the google drive link, but you can train that on your own with the data we provided if you need these models. I hope this helps.

**Comment by WanyiLi** [comment]
Hi, QingKai
The grasp_planner works while using command "roslaunch prob_grasp_planner grasp_active_learning.launch".
However, bugs still exist in moveit for motion planning, grasp_pipeline servers and  grasp_pipeline client. Details are as follows.

1. moveit for motion planning.
[ERROR] : Could not find the planner configuration 'None' on the param server
[ WARN] : Unable to transform object from frame 'ground_plane__link' to planning frame 'world' (Could not find a connection between 'world' and 'ground_plane__link' because they are not part of the same tree.Tf has two or more unconnected trees.)

2.grasp_pipeline servers
running to scene.add_mesh('obj_mesh', req.object_pose_world, req.object_mesh_path)  of manage_moveit_scene_server.py, manage_moveit_scene_node-3] process has died. 

3.grasp_pipeline client 
Service create_moveit_scene call failed

besides the used lbr4_allegro_moveit_config package is from your github site, https://github.com/QingkaiLu/lbr4_allegro_moveit_config.

Could you provide some suggestion?
Thanks.
